# Generated by Django 2.2.4 on 2020-06-11 12:37

import ckeditor.fields
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='contentt',
            field=ckeditor.fields.RichTextField(default='testt'),
            preserve_default=False,
        ),
    ]
