# Generated by Django 2.2.4 on 2020-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200611_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='testsummer',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
